/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PaySlugRouteImport } from './routes/pay.$slug'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalMerchantRouteImport } from './routes/legal.merchant'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as DashboardWebhooksRouteImport } from './routes/dashboard.webhooks'
import { Route as DashboardTransactionsRouteImport } from './routes/dashboard.transactions'
import { Route as DashboardTeamRouteImport } from './routes/dashboard.team'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRefundsRouteImport } from './routes/dashboard.refunds'
import { Route as DashboardPaymentLinksRouteImport } from './routes/dashboard.payment-links'
import { Route as DashboardLiveModeRouteImport } from './routes/dashboard.live-mode'
import { Route as DashboardInternationalRouteImport } from './routes/dashboard.international'
import { Route as DashboardDevelopersRouteImport } from './routes/dashboard.developers'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardBusinessRouteImport } from './routes/dashboard.business'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DashboardSettingsProviderRouteImport } from './routes/dashboard.settings.provider'
import { Route as DashboardSettingsCurrenciesRouteImport } from './routes/dashboard.settings.currencies'
import { Route as PaySlugStatusRefRouteImport } from './routes/pay.$slug.status.$ref'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks/razorpay'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PaySlugRoute = PaySlugRouteImport.update({
  id: '/pay/$slug',
  path: '/pay/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMerchantRoute = LegalMerchantRouteImport.update({
  id: '/legal/merchant',
  path: '/legal/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebhooksRoute = DashboardWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTransactionsRoute = DashboardTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRefundsRoute = DashboardRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentLinksRoute = DashboardPaymentLinksRouteImport.update({
  id: '/payment-links',
  path: '/payment-links',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveModeRoute = DashboardLiveModeRouteImport.update({
  id: '/live-mode',
  path: '/live-mode',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInternationalRoute = DashboardInternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDevelopersRoute = DashboardDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBusinessRoute = DashboardBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsProviderRoute =
  DashboardSettingsProviderRouteImport.update({
    id: '/provider',
    path: '/provider',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsCurrenciesRoute =
  DashboardSettingsCurrenciesRouteImport.update({
    id: '/currencies',
    path: '/currencies',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const PaySlugStatusRefRoute = PaySlugStatusRefRouteImport.update({
  id: '/status/$ref',
  path: '/status/$ref',
  getParentRoute: () => PaySlugRoute,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/developers': typeof DashboardDevelopersRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/live-mode': typeof DashboardLiveModeRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/merchant': typeof LegalMerchantRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/dashboard/settings/provider': typeof DashboardSettingsProviderRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/pay/$slug/status/$ref': typeof PaySlugStatusRefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/developers': typeof DashboardDevelopersRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/live-mode': typeof DashboardLiveModeRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/merchant': typeof LegalMerchantRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/dashboard/settings/provider': typeof DashboardSettingsProviderRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/pay/$slug/status/$ref': typeof PaySlugStatusRefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/company': typeof CompanyRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/developers': typeof DevelopersRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/international': typeof InternationalRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/business': typeof DashboardBusinessRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/developers': typeof DashboardDevelopersRoute
  '/dashboard/international': typeof DashboardInternationalRoute
  '/dashboard/live-mode': typeof DashboardLiveModeRoute
  '/dashboard/payment-links': typeof DashboardPaymentLinksRoute
  '/dashboard/refunds': typeof DashboardRefundsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/transactions': typeof DashboardTransactionsRoute
  '/dashboard/webhooks': typeof DashboardWebhooksRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/merchant': typeof LegalMerchantRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/terms': typeof LegalTermsRoute
  '/pay/$slug': typeof PaySlugRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/currencies': typeof DashboardSettingsCurrenciesRoute
  '/dashboard/settings/provider': typeof DashboardSettingsProviderRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/pay/$slug/status/$ref': typeof PaySlugStatusRefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/company'
    | '/dashboard'
    | '/developers'
    | '/forgot-password'
    | '/international'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/business'
    | '/dashboard/customers'
    | '/dashboard/developers'
    | '/dashboard/international'
    | '/dashboard/live-mode'
    | '/dashboard/payment-links'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/webhooks'
    | '/legal/cookies'
    | '/legal/merchant'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/pay/$slug'
    | '/dashboard/'
    | '/dashboard/settings/currencies'
    | '/dashboard/settings/provider'
    | '/api/public/webhooks/razorpay'
    | '/pay/$slug/status/$ref'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/company'
    | '/developers'
    | '/forgot-password'
    | '/international'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/business'
    | '/dashboard/customers'
    | '/dashboard/developers'
    | '/dashboard/international'
    | '/dashboard/live-mode'
    | '/dashboard/payment-links'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/webhooks'
    | '/legal/cookies'
    | '/legal/merchant'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/pay/$slug'
    | '/dashboard'
    | '/dashboard/settings/currencies'
    | '/dashboard/settings/provider'
    | '/api/public/webhooks/razorpay'
    | '/pay/$slug/status/$ref'
  id:
    | '__root__'
    | '/'
    | '/company'
    | '/dashboard'
    | '/developers'
    | '/forgot-password'
    | '/international'
    | '/login'
    | '/payments'
    | '/pricing'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard/analytics'
    | '/dashboard/business'
    | '/dashboard/customers'
    | '/dashboard/developers'
    | '/dashboard/international'
    | '/dashboard/live-mode'
    | '/dashboard/payment-links'
    | '/dashboard/refunds'
    | '/dashboard/settings'
    | '/dashboard/team'
    | '/dashboard/transactions'
    | '/dashboard/webhooks'
    | '/legal/cookies'
    | '/legal/merchant'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/terms'
    | '/pay/$slug'
    | '/dashboard/'
    | '/dashboard/settings/currencies'
    | '/dashboard/settings/provider'
    | '/api/public/webhooks/razorpay'
    | '/pay/$slug/status/$ref'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompanyRoute: typeof CompanyRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DevelopersRoute: typeof DevelopersRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InternationalRoute: typeof InternationalRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMerchantRoute: typeof LegalMerchantRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalTermsRoute: typeof LegalTermsRoute
  PaySlugRoute: typeof PaySlugRouteWithChildren
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/pay/$slug': {
      id: '/pay/$slug'
      path: '/pay/$slug'
      fullPath: '/pay/$slug'
      preLoaderRoute: typeof PaySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/merchant': {
      id: '/legal/merchant'
      path: '/legal/merchant'
      fullPath: '/legal/merchant'
      preLoaderRoute: typeof LegalMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/webhooks': {
      id: '/dashboard/webhooks'
      path: '/webhooks'
      fullPath: '/dashboard/webhooks'
      preLoaderRoute: typeof DashboardWebhooksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/transactions': {
      id: '/dashboard/transactions'
      path: '/transactions'
      fullPath: '/dashboard/transactions'
      preLoaderRoute: typeof DashboardTransactionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/refunds': {
      id: '/dashboard/refunds'
      path: '/refunds'
      fullPath: '/dashboard/refunds'
      preLoaderRoute: typeof DashboardRefundsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payment-links': {
      id: '/dashboard/payment-links'
      path: '/payment-links'
      fullPath: '/dashboard/payment-links'
      preLoaderRoute: typeof DashboardPaymentLinksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live-mode': {
      id: '/dashboard/live-mode'
      path: '/live-mode'
      fullPath: '/dashboard/live-mode'
      preLoaderRoute: typeof DashboardLiveModeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/international': {
      id: '/dashboard/international'
      path: '/international'
      fullPath: '/dashboard/international'
      preLoaderRoute: typeof DashboardInternationalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/developers': {
      id: '/dashboard/developers'
      path: '/developers'
      fullPath: '/dashboard/developers'
      preLoaderRoute: typeof DashboardDevelopersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/business': {
      id: '/dashboard/business'
      path: '/business'
      fullPath: '/dashboard/business'
      preLoaderRoute: typeof DashboardBusinessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings/provider': {
      id: '/dashboard/settings/provider'
      path: '/provider'
      fullPath: '/dashboard/settings/provider'
      preLoaderRoute: typeof DashboardSettingsProviderRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/currencies': {
      id: '/dashboard/settings/currencies'
      path: '/currencies'
      fullPath: '/dashboard/settings/currencies'
      preLoaderRoute: typeof DashboardSettingsCurrenciesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/pay/$slug/status/$ref': {
      id: '/pay/$slug/status/$ref'
      path: '/status/$ref'
      fullPath: '/pay/$slug/status/$ref'
      preLoaderRoute: typeof PaySlugStatusRefRouteImport
      parentRoute: typeof PaySlugRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsCurrenciesRoute: typeof DashboardSettingsCurrenciesRoute
  DashboardSettingsProviderRoute: typeof DashboardSettingsProviderRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsCurrenciesRoute: DashboardSettingsCurrenciesRoute,
  DashboardSettingsProviderRoute: DashboardSettingsProviderRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardBusinessRoute: typeof DashboardBusinessRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardDevelopersRoute: typeof DashboardDevelopersRoute
  DashboardInternationalRoute: typeof DashboardInternationalRoute
  DashboardLiveModeRoute: typeof DashboardLiveModeRoute
  DashboardPaymentLinksRoute: typeof DashboardPaymentLinksRoute
  DashboardRefundsRoute: typeof DashboardRefundsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTransactionsRoute: typeof DashboardTransactionsRoute
  DashboardWebhooksRoute: typeof DashboardWebhooksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardBusinessRoute: DashboardBusinessRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardDevelopersRoute: DashboardDevelopersRoute,
  DashboardInternationalRoute: DashboardInternationalRoute,
  DashboardLiveModeRoute: DashboardLiveModeRoute,
  DashboardPaymentLinksRoute: DashboardPaymentLinksRoute,
  DashboardRefundsRoute: DashboardRefundsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTransactionsRoute: DashboardTransactionsRoute,
  DashboardWebhooksRoute: DashboardWebhooksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PaySlugRouteChildren {
  PaySlugStatusRefRoute: typeof PaySlugStatusRefRoute
}

const PaySlugRouteChildren: PaySlugRouteChildren = {
  PaySlugStatusRefRoute: PaySlugStatusRefRoute,
}

const PaySlugRouteWithChildren =
  PaySlugRoute._addFileChildren(PaySlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompanyRoute: CompanyRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DevelopersRoute: DevelopersRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InternationalRoute: InternationalRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMerchantRoute: LegalMerchantRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalTermsRoute: LegalTermsRoute,
  PaySlugRoute: PaySlugRouteWithChildren,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
